### ISSUE TITLE
Для чего здесь используется uint16?

### ISSUE THREAD

**Issue by Anatoliyphp** [dmcharlie19/SeondTask#5]
https://github.com/dmcharlie19/SeondTask/blob/4841dbce663169205a5f524bfd9b7def6b698c20/SeondTask/BaseComponents.cs#L12

**Comment by dmcharlie19** [comment]
привычка после c++ и ограниченного количества памяти) когда в распоряжение всего 1 кб стека думаешь о каждом байте.
как я понимаю в шарпе чаще вего используют просто Int, поенял на int
