### ISSUE TITLE
Для чего здесь приведение типов?

### ISSUE THREAD

**Issue by Anatoliyphp** [dmcharlie19/SeondTask#8]
https://github.com/dmcharlie19/SeondTask/blob/4841dbce663169205a5f524bfd9b7def6b698c20/SeondTask/Computer.cs#L24

**Comment by dmcharlie19** [comment]
потому что поле count имеет тип int

**Comment by dmcharlie19** [comment]
поменял в методе CheckRamUnitCount тип параметра на Int
